# Generated by Django 5.2.17 on 2026-10-01 12:37

import core.fields
import django.contrib.postgres.fields
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=60, unique=True, verbose_name="identificador"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("html_watch", "Página monitorada"),
                            ("dataset", "Conjunto de dados"),
                            ("seed_csv", "CSV de sementes"),
                            ("search", "Busca"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL base"
                    ),
                ),
                (
                    "terms_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL dos termos de uso"
                    ),
                ),
                (
                    "robots_ok",
                    models.BooleanField(
                        default=False,
                        help_text="robots.txt e termos de uso conferidos e permitem a coleta.",
                        verbose_name="coleta permitida",
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: ODbL, CC-BY.",
                        max_length=60,
                        verbose_name="licença",
                    ),
                ),
                (
                    "reliability",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1 a 5, julgamento humano documentado em docs/research.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="confiabilidade",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="habilitada"),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("daily", "Diária"),
                            ("weekly", "Semanal"),
                            ("manual", "Manual (sob demanda)"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="agendamento",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configuração"
                    ),
                ),
            ],
            options={
                "verbose_name": "fonte",
                "verbose_name_plural": "fontes",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="ID da entidade"),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Afirmação sobre a entidade. Ex.: deadline_at, offers_high_school.",
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*(?:\\.[a-z0-9_]+)*$",
                                "Use minúsculas, números e _ (ex.: deadline_at, contact.email).",
                            )
                        ],
                        verbose_name="campo",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text='Em JSON: "2026-11-15" (texto entre aspas), 120, true ou ["a", "b"].',
                        verbose_name="valor",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("observed", "Observado"),
                            ("inferred", "Inferido"),
                            ("manual", "Manual"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="URL da fonte"
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nome da fonte"
                    ),
                ),
                (
                    "retrieved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="coletado em"
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Trecho copiado da fonte, sem alterações (até 500 caracteres).",
                        max_length=500,
                        verbose_name="trecho literal",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="Como o valor foi obtido. Ex.: connector:devpost, rule:cnae_map, human.",
                        max_length=120,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(?:(?:connector|regex|rule|llm):\\S+|human)$",
                                "Use connector:<fonte>, regex:<nome>, rule:<nome>, llm:<modelo>@<prompt> ou human.",
                            )
                        ],
                        verbose_name="método",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="De 0 a 1.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="confiança",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="O trecho foi encontrado no texto da fonte?",
                        verbose_name="citação verificada",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "core"),
                            ("model__in", ("organization", "opportunity")),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="tipo da entidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidência",
                "verbose_name_plural": "evidências",
                "ordering": ["-retrieved_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="razão social"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("school", "Escola"),
                            ("sesc", "SESC"),
                            ("company", "Empresa"),
                            ("university", "Universidade"),
                            ("public_body", "Órgão público"),
                            ("ngo", "ONG / associação"),
                            ("event_organizer", "Organizador de eventos"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="Aceita a máscara; é guardado só com letras e dígitos (14 posições).",
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "inep_code",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8}$", "O código INEP tem 8 dígitos."
                            )
                        ],
                        verbose_name="código INEP",
                    ),
                ),
                (
                    "osm_id",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: way/123456789.",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="ID no OpenStreetMap",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="segmento"
                    ),
                ),
                (
                    "cnae_main",
                    models.CharField(
                        blank=True,
                        help_text="A comparação de CNAE ignora a pontuação (85.99-6/03 = 8599603).",
                        max_length=12,
                        verbose_name="CNAE principal",
                    ),
                ),
                (
                    "size_hint",
                    models.CharField(
                        choices=[
                            ("micro", "Micro"),
                            ("small", "Pequena"),
                            ("medium", "Média"),
                            ("large", "Grande"),
                            ("unknown", "Desconhecido"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="porte (estimado)",
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="município"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$",
                                "Use a sigla da UF com duas letras maiúsculas.",
                            )
                        ],
                        verbose_name="UF",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="endereço")),
                (
                    "lat",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=500, verbose_name="site"),
                ),
                (
                    "website_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Não pesquisado"),
                            ("found", "Encontrado"),
                            ("not_found", "Não encontrado"),
                            ("ambiguous", "Ambíguo"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="situação do site",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Ex.: SESC-SP, SENAC-SP, Centro Paula Souza.",
                        max_length=80,
                        verbose_name="rede",
                    ),
                ),
                (
                    "similarity_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=60),
                        blank=True,
                        default=list,
                        help_text="Separe por vírgula. Ex.: sistema_s, cultural_publico, educacao_nao_formal.",
                        size=None,
                        verbose_name="tags de similaridade",
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        choices=[
                            ("never_contacted", "Nunca contatada"),
                            ("contacted", "Contatada"),
                            ("in_conversation", "Em conversa"),
                            ("proposal_sent", "Proposta enviada"),
                            ("client", "Cliente"),
                            ("lost", "Perdida"),
                            ("do_not_contact", "Não contatar"),
                        ],
                        default="never_contacted",
                        max_length=20,
                        verbose_name="relacionamento",
                    ),
                ),
                (
                    "last_interaction_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última interação"
                    ),
                ),
                (
                    "next_action_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="próxima ação em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Para redes com várias unidades (ex.: SESC-SP → SESC Bauru).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.organization",
                        verbose_name="organização-mãe",
                    ),
                ),
                (
                    "first_seen_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="core.source",
                        verbose_name="fonte da primeira descoberta",
                    ),
                ),
            ],
            options={
                "verbose_name": "organização",
                "verbose_name_plural": "organizações",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("edital", "Edital"),
                            ("hackathon", "Hackathon"),
                            ("game_jam", "Game jam"),
                            ("event", "Evento"),
                            ("program", "Programa"),
                            ("contest", "Concurso"),
                            ("procurement", "Licitação"),
                            ("call_for_partners", "Chamada para parceiros"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="título")),
                (
                    "organizer_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome do organizador"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="resumo")),
                (
                    "categories",
                    core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("culture", "Cultura"),
                                ("innovation", "Inovação"),
                                ("education", "Educação"),
                                ("games", "Jogos"),
                                ("technology", "Tecnologia"),
                                ("entrepreneurship", "Empreendedorismo"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="categorias",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_person", "Presencial"),
                            ("hybrid", "Híbrida"),
                            ("unknown", "Não informada"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="modalidade",
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="município"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$",
                                "Use a sigla da UF com duas letras maiúsculas.",
                            )
                        ],
                        verbose_name="UF",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("municipal", "Municipal"),
                            ("regional", "Regional"),
                            ("state", "Estadual"),
                            ("national", "Nacional"),
                            ("international", "Internacional"),
                        ],
                        max_length=15,
                        verbose_name="abrangência",
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="abertura das inscrições"
                    ),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="prazo final"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="início do evento/projeto"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fim do evento/projeto"
                    ),
                ),
                (
                    "eligibility_text",
                    models.TextField(blank=True, verbose_name="texto de elegibilidade"),
                ),
                (
                    "requires_legal_entity",
                    models.CharField(
                        choices=[
                            ("yes", "Sim"),
                            ("no", "Não"),
                            ("unknown", "Não informado"),
                        ],
                        default="unknown",
                        max_length=7,
                        verbose_name="exige CNPJ",
                    ),
                ),
                (
                    "eligible_legal_forms",
                    core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PF", "Pessoa física"),
                                ("MEI", "MEI"),
                                ("ME", "Microempresa (ME)"),
                                ("EPP", "Empresa de pequeno porte (EPP)"),
                                (
                                    "OTHER_COMPANY",
                                    "Demais empresas (médio e grande porte)",
                                ),
                                (
                                    "OSC",
                                    "Associação, ONG, cooperativa ou instituto (OSC)",
                                ),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        help_text="Vazio = nenhuma restrição conhecida.",
                        size=None,
                        verbose_name="naturezas jurídicas aceitas",
                    ),
                ),
                (
                    "exclusive_small_business",
                    models.BooleanField(
                        blank=True,
                        help_text="Desconhecido quando não informado.",
                        null=True,
                        verbose_name="cota exclusiva ME/EPP/MEI",
                    ),
                ),
                (
                    "min_company_age_months",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="idade mínima da empresa (meses)",
                    ),
                ),
                (
                    "required_cnaes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12),
                        blank=True,
                        default=list,
                        help_text="Separe por vírgula. A comparação ignora a pontuação. Vazio = sem exigência.",
                        size=None,
                        verbose_name="CNAEs exigidos (prefixos)",
                    ),
                ),
                (
                    "eligible_regions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        blank=True,
                        default=list,
                        help_text="UFs ou municípios, separados por vírgula. Vazio = sem restrição conhecida.",
                        size=None,
                        verbose_name="regiões elegíveis",
                    ),
                ),
                (
                    "requirements_text",
                    models.TextField(blank=True, verbose_name="requisitos"),
                ),
                (
                    "prize_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="prêmio/valor (texto)"
                    ),
                ),
                (
                    "prize_amount_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="valor numérico (R$)",
                    ),
                ),
                (
                    "benefits",
                    core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("money", "Dinheiro"),
                                ("contract", "Contrato"),
                                ("prize", "Prêmio"),
                                ("visibility", "Visibilidade"),
                                ("networking", "Networking"),
                                ("mentoring", "Mentoria"),
                                ("infrastructure", "Infraestrutura"),
                                ("acceleration", "Aceleração"),
                                ("partnership", "Parceria"),
                                ("clients", "Clientes"),
                                ("portfolio", "Portfólio"),
                                ("certification", "Certificação"),
                                ("investors", "Investidores"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="benefícios",
                    ),
                ),
                (
                    "participation_cost_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="custo de participação"
                    ),
                ),
                (
                    "effort_estimate",
                    models.CharField(
                        choices=[
                            ("low", "Baixo"),
                            ("medium", "Médio"),
                            ("high", "Alto"),
                            ("unknown", "Desconhecido"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="esforço estimado",
                    ),
                ),
                (
                    "official_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL oficial"
                    ),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True,
                        help_text="Identifica a oportunidade para evitar duplicatas. Em branco = gerada (URL oficial, ou organizador + título + prazo).",
                        max_length=600,
                        unique=True,
                        verbose_name="chave canônica",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("upcoming", "Em breve"),
                            ("closed", "Encerrada"),
                            ("unknown", "Desconhecida"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "extraction_version",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="versão da extração"
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="vista pela primeira vez em",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="vista pela última vez em",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="core.organization",
                        verbose_name="organizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "oportunidade",
                "verbose_name_plural": "oportunidades",
                "ordering": ["-first_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContactPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("phone", "Telefone"),
                            ("whatsapp", "WhatsApp"),
                            ("contact_form", "Formulário de contato"),
                            ("website", "Site"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin_company", "LinkedIn da organização"),
                            ("youtube", "YouTube"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("value", models.CharField(max_length=500, verbose_name="valor")),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Ex.: "Secretaria".',
                        max_length=120,
                        verbose_name="rótulo",
                    ),
                ),
                (
                    "is_personal",
                    models.BooleanField(
                        default=False,
                        help_text="E-mail/telefone de pessoa identificada (LGPD): prefira contatos institucionais.",
                        verbose_name="dado pessoal",
                    ),
                ),
                (
                    "role_hint",
                    models.CharField(
                        blank=True,
                        help_text="Só se publicado pela própria organização; nunca inventado.",
                        max_length=120,
                        verbose_name="cargo/setor",
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verificado em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("bounced", "Devolvido"),
                            ("invalid", "Inválido"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contact_points",
                        to="core.evidence",
                        verbose_name="evidência",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_points",
                        to="core.organization",
                        verbose_name="organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
                "ordering": ["organization", "kind", "value"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Chave estável usada por importações e regras: não renomeie.",
                        max_length=60,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("games", "Jogos"),
                            ("education", "Educação"),
                            ("software", "Software"),
                            ("web", "Web"),
                            ("other", "Outro"),
                        ],
                        max_length=12,
                        verbose_name="categoria",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        blank=True,
                        default=list,
                        help_text="Separe por vírgula. Usadas pelas regras de matching (E20).",
                        size=None,
                        verbose_name="palavras-chave",
                    ),
                ),
                (
                    "target_org_kinds",
                    core.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("school", "Escola"),
                                ("sesc", "SESC"),
                                ("company", "Empresa"),
                                ("university", "Universidade"),
                                ("public_body", "Órgão público"),
                                ("ngo", "ONG / associação"),
                                ("event_organizer", "Organizador de eventos"),
                                ("other", "Outro"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="tipos de organização-alvo",
                    ),
                ),
                (
                    "target_cnaes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12),
                        blank=True,
                        default=list,
                        help_text="CNAEs das organizações que costumam comprar. Vazio = qualquer.",
                        size=None,
                        verbose_name="CNAEs-alvo (prefixos)",
                    ),
                ),
                (
                    "geo_profile",
                    models.CharField(
                        choices=[
                            ("onsite_recurring", "Presencial recorrente"),
                            ("onsite_event", "Presencial pontual"),
                            ("online", "Online"),
                            ("remote_service", "Serviço remoto"),
                        ],
                        help_text="Presencial recorrente: cursos e oficinas. Presencial pontual: game jam e eventos. Online: distância irrelevante. Serviço remoto: software, web e jogos sob encomenda. Ver docs/architecture/geo-relevance.md.",
                        max_length=20,
                        verbose_name="perfil geográfico",
                    ),
                ),
                (
                    "typical_ticket_min_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ticket típico — mínimo (R$)",
                    ),
                ),
                (
                    "typical_ticket_max_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ticket típico — máximo (R$)",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "mei_coverage",
                    models.CharField(
                        choices=[
                            ("covered", "Coberto pelo MEI"),
                            ("verify", "Verificar com o contador"),
                            ("not_covered", "Exigiria ME"),
                        ],
                        default="verify",
                        help_text="Se o enquadramento atual cobre vender este serviço (ADR-015).",
                        max_length=12,
                        verbose_name="cobertura pelo MEI",
                    ),
                ),
                (
                    "required_cnae_prefixes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=12),
                        blank=True,
                        default=list,
                        help_text="Qualquer um deles cobre o serviço. A comparação ignora a pontuação.",
                        size=None,
                        verbose_name="CNAEs exigidos da empresa (prefixos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "serviço do catálogo",
                "verbose_name_plural": "serviços do catálogo",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("typical_ticket_min_brl__isnull", True),
                            ("typical_ticket_max_brl__isnull", True),
                            (
                                "typical_ticket_max_brl__gte",
                                models.F("typical_ticket_min_brl"),
                            ),
                            _connector="OR",
                        ),
                        name="service_ticket_max_gte_min",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de {"text": ..., "evidence_id": ..., "kind": "observed|inferred"}.',
                        verbose_name="motivos",
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        help_text="De 0 a 1.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="força",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="rules_v1",
                        help_text="Ex.: rules_v1, llm_v1.",
                        max_length=30,
                        verbose_name="método",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.organization",
                        verbose_name="organização",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.serviceoffering",
                        verbose_name="serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "ordering": ["-strength", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "E-mail"),
                            ("phone", "Telefone"),
                            ("domain", "Domínio"),
                            ("organization", "Organização"),
                        ],
                        max_length=15,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="E-mail, telefone, domínio (vale também para subdomínios) ou CNPJ/nome da organização.",
                        max_length=255,
                        verbose_name="valor",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="motivo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "supressão (opt-out)",
                "verbose_name_plural": "supressões (opt-out)",
                "ordering": ["kind", "value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "value"), name="uniq_suppression_kind_value"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Triage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="ID da entidade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nova"),
                            ("interesting", "Interessante"),
                            ("discarded", "Descartada"),
                            ("acting", "Em andamento"),
                            ("done", "Concluída"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "discard_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_relevant", "Não relevante"),
                            ("too_far", "Longe demais"),
                            ("ineligible", "Inelegível"),
                            ("too_much_effort", "Esforço demais"),
                            ("low_value", "Pouco valor"),
                            ("duplicate", "Duplicada"),
                            ("bad_data", "Dados ruins"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="motivo do descarte",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="nota")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decidido em"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "core"),
                            ("model__in", ("organization", "opportunity")),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="tipo da entidade",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decidido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "triagem",
                "verbose_name_plural": "triagens",
                "ordering": ["-decided_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["content_type", "object_id", "field"],
                name="evidence_entity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="evidence_confidence_in_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "observed"), _negated=True),
                    models.Q(("source_url", ""), _negated=True),
                    _connector="OR",
                ),
                name="evidence_observed_has_source_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactpoint",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind", "value"),
                name="uniq_contact_org_kind_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("organization", "service", "method"),
                name="uniq_match_org_service_method",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("strength__gte", 0), ("strength__lte", 1)),
                name="match_strength_in_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="triage",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="uniq_triage_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="triage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "discarded"), _negated=True),
                    models.Q(("discard_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="triage_discard_needs_reason",
            ),
        ),
    ]
