# Generated by Django 5.2.17 on 2026-10-01 13:24

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[],
            options={
                "verbose_name": "próxima ação",
                "verbose_name_plural": "próximas ações",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.organization",),
        ),
        migrations.AlterField(
            model_name="organization",
            name="last_interaction_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="última interação"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="next_action_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="próxima ação em"
            ),
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        choices=[
                            ("PF", "Pessoa física"),
                            ("MEI", "MEI"),
                            ("ME", "Microempresa (ME)"),
                            ("EPP", "Empresa de pequeno porte (EPP)"),
                            ("OTHER_COMPANY", "Demais empresas (médio e grande porte)"),
                            ("OSC", "Associação, ONG, cooperativa ou instituto (OSC)"),
                        ],
                        default="MEI",
                        max_length=14,
                        verbose_name="natureza jurídica",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativa", "Ativa"), ("outra", "Outra situação")],
                        default="ativa",
                        max_length=5,
                        verbose_name="situação",
                    ),
                ),
                (
                    "opened_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de abertura"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        help_text="Só pelo .env/admin; nunca no git. Aceita a máscara.",
                        max_length=18,
                        null=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="razão social"
                    ),
                ),
                (
                    "hq_municipality",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="município da sede"
                    ),
                ),
                (
                    "hq_uf",
                    models.CharField(
                        blank=True,
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$",
                                "Use a sigla da UF com duas letras maiúsculas.",
                            )
                        ],
                        verbose_name="UF da sede",
                    ),
                ),
                (
                    "annual_revenue_cap_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="teto de faturamento anual (R$)",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, max_length=500, verbose_name="site"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail de contato"
                    ),
                ),
                (
                    "activity_mode",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="modalidade de atuação"
                    ),
                ),
                (
                    "primary_cnae",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="CNAE principal"
                    ),
                ),
                (
                    "cnaes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de {"code", "description", "role": "principal|secundario", "occupation"}.',
                        verbose_name="CNAEs",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "perfil da empresa",
                "verbose_name_plural": "perfil da empresa",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="company_profile_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Chave estável usada pela importação: não renomeie.",
                        max_length=60,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="título")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("game", "Jogo"),
                            ("course", "Curso/oficina"),
                            ("prototype", "Protótipo"),
                            ("website", "Site"),
                            ("system", "Sistema"),
                            ("other", "Outro"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ano"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "public_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL pública"
                    ),
                ),
                (
                    "url_source",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: informado pelo titular.",
                        max_length=120,
                        verbose_name="origem da URL",
                    ),
                ),
                (
                    "capability_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=60),
                        blank=True,
                        default=list,
                        help_text="Separe por vírgula. Ex.: jogos, ensino_presencial.",
                        size=None,
                        verbose_name="capacidades",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Só marque se já é público.",
                        verbose_name="pode ser citado em propostas",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Completo"),
                            ("pending", "Dados pendentes"),
                            ("description_pending", "Descrição pendente"),
                            ("to_confirm", "A confirmar"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="situação dos dados",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="portfolio_items",
                        to="core.serviceoffering",
                        verbose_name="serviços comprovados",
                    ),
                ),
            ],
            options={
                "verbose_name": "item de portfólio",
                "verbose_name_plural": "itens de portfólio",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="portfolio_refs",
            field=models.ManyToManyField(
                blank=True,
                related_name="matches",
                to="core.portfolioitem",
                verbose_name="portfólio como prova",
            ),
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateField(
                        blank=True,
                        help_text="Em branco se ainda não confirmada.",
                        null=True,
                        verbose_name="data",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("proposal_sent", "Proposta enviada"),
                            ("meeting", "Reunião"),
                            ("message", "Mensagem"),
                            ("call", "Ligação"),
                            ("visit", "Visita"),
                            ("course_delivered", "Curso/oficina realizado"),
                            ("event_participation", "Participação em evento"),
                            ("response_received", "Resposta recebida"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "E-mail"),
                            ("phone", "Telefone"),
                            ("whatsapp", "WhatsApp"),
                            ("in_person", "Presencial"),
                            ("form", "Formulário do site"),
                            ("other", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                (
                    "contact_name_role",
                    models.CharField(
                        blank=True,
                        help_text="Dado pessoal: prefira o cargo ao nome e registre só o necessário.",
                        max_length=120,
                        verbose_name="cargo/papel do contato",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="resumo")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("positive", "Positivo"),
                            ("negative", "Negativo"),
                            ("no_response", "Sem resposta"),
                            ("won", "Fechado (ganho)"),
                            ("lost", "Perdido"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="resultado",
                    ),
                ),
                (
                    "next_action",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="próxima ação"
                    ),
                ),
                (
                    "next_action_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="próxima ação em"
                    ),
                ),
                (
                    "attachments_url",
                    models.URLField(
                        blank=True,
                        help_text="Ex.: proposta no Drive da empresa. Nunca anexe arquivos aqui.",
                        max_length=500,
                        verbose_name="link dos anexos",
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmado"),
                            ("pending", "Pendente de confirmação"),
                        ],
                        default="confirmed",
                        max_length=10,
                        verbose_name="situação do registro",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "contact_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="core.contactpoint",
                        verbose_name="contato",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="core.organization",
                        verbose_name="organização",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="core.serviceoffering",
                        verbose_name="serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "interação",
                "verbose_name_plural": "interações",
                "ordering": [
                    models.OrderBy(
                        models.F("occurred_at"), descending=True, nulls_first=True
                    ),
                    "-created_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["next_action_at"], name="interaction_next_action_idx"
                    )
                ],
            },
        ),
    ]
