# Generated by Django 5.2.17 on 2026-10-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_collection"),
        ("core", "0002_commercial_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="raw_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Cópia (texto) da página de onde a afirmação saiu, se foi coletada.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_items",
                to="collection.rawdocument",
                verbose_name="documento bruto",
            ),
        ),
    ]
