# Generated by Django 5.2.17 on 2026-10-01 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ibge_code",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000),
                            django.core.validators.MaxValueValidator(9999999),
                        ],
                        verbose_name="código IBGE",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "name_key",
                    models.CharField(
                        editable=False, max_length=120, verbose_name="nome normalizado"
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "Sigla da UF em maiúsculas."
                            )
                        ],
                        verbose_name="UF",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("N", "Norte"),
                            ("NE", "Nordeste"),
                            ("SE", "Sudeste"),
                            ("S", "Sul"),
                            ("CO", "Centro-Oeste"),
                        ],
                        max_length=2,
                        verbose_name="região",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "is_capital",
                    models.BooleanField(default=False, verbose_name="capital"),
                ),
            ],
            options={
                "verbose_name": "município",
                "verbose_name_plural": "municípios",
                "ordering": ["uf", "name"],
                "indexes": [
                    models.Index(fields=["name_key"], name="municipality_name_key_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name_key", "uf"), name="uniq_municipality_name_uf"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolvido sozinho a partir do nome e da UF quando possível; corrija se errado.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="core.municipality",
                verbose_name="município (IBGE)",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolvido sozinho a partir do nome e da UF quando possível; corrija se errado.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="core.municipality",
                verbose_name="município (IBGE)",
            ),
        ),
    ]
