# Generated by Django 5.2.17 on 2026-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_municipality"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contacts_checked_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Última vez que `extract_contacts` leu o site (E19).",
                null=True,
                verbose_name="contatos verificados em",
            ),
        ),
    ]
