# Generated by Django 5.2.17 on 2026-10-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organization_contacts_checked_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("interesting", "Interessante"),
                            ("contacted", "Contato"),
                            ("responded", "Respondeu"),
                            ("meeting", "Reunião"),
                            ("proposal", "Proposta"),
                            ("negotiation", "Negociação"),
                            ("won", "Fechado (ganho)"),
                            ("lost", "Perdido"),
                        ],
                        default="interesting",
                        max_length=12,
                        verbose_name="estágio",
                    ),
                ),
                (
                    "peak_stage",
                    models.CharField(
                        choices=[
                            ("interesting", "Interessante"),
                            ("contacted", "Contato"),
                            ("responded", "Respondeu"),
                            ("meeting", "Reunião"),
                            ("proposal", "Proposta"),
                            ("negotiation", "Negociação"),
                            ("won", "Fechado (ganho)"),
                            ("lost", "Perdido"),
                        ],
                        editable=False,
                        max_length=12,
                        verbose_name="estágio mais alto alcançado",
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="valor estimado (R$)",
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_response", "Sem resposta"),
                            ("no_budget", "Sem orçamento"),
                            ("chose_other", "Escolheram outro"),
                            ("not_now", "Não é o momento"),
                            ("opt_out", "Pediu para não ser contatado"),
                            ("other", "Outro"),
                        ],
                        max_length=12,
                        verbose_name="motivo da perda",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="observação"
                    ),
                ),
                (
                    "stage_changed_at",
                    models.DateTimeField(
                        editable=False, verbose_name="estágio mudou em"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="fechado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="core.opportunity",
                        verbose_name="oportunidade de origem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="core.organization",
                        verbose_name="organização",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="core.serviceoffering",
                        verbose_name="serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "negócio",
                "verbose_name_plural": "negócios (pipeline)",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="interaction",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                help_text="Pipeline (E23): agrupa as interações de um mesmo negócio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interactions",
                to="core.deal",
                verbose_name="negócio",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["stage"], name="deal_stage_idx"),
        ),
    ]
