# Generated by Django 5.2.17 on 2026-10-04 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_deal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "E-mail"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("first_contact", "Primeiro contato"),
                            ("follow_up", "Retomada"),
                        ],
                        max_length=14,
                        verbose_name="modo",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="assunto"
                    ),
                ),
                ("body", models.TextField(verbose_name="texto")),
                (
                    "claims",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de {"text", "about", "facts": [ids]}.',
                        verbose_name="afirmações e fatos",
                    ),
                ),
                (
                    "facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="fatos enviados ao modelo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Válido"),
                            ("rejected", "Rejeitado pelo validador"),
                        ],
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "validation_issues",
                    models.JSONField(
                        blank=True, default=list, verbose_name="problemas do validador"
                    ),
                ),
                (
                    "attempts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Estratégias tentadas e por que caíram.",
                        verbose_name="tentativas",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="estratégia"
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="versão do prompt"
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="custo (US$)",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usable", "Usável com edição leve"),
                            ("rewrite", "Precisa reescrever"),
                            ("unusable", "Inútil"),
                        ],
                        max_length=10,
                        verbose_name="avaliação humana",
                    ),
                ),
                (
                    "rating_note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nota da avaliação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gerado por",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_drafts",
                        to="core.organization",
                        verbose_name="organização",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.serviceoffering",
                        verbose_name="serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "rascunho de abordagem",
                "verbose_name_plural": "rascunhos de abordagem",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
