# Generated by Django 5.2.17 on 2026-10-01 13:38

import collection.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_commercial_memory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="início"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="fim"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Em andamento"),
                            ("ok", "Concluída"),
                            ("partial", "Parcial (houve falhas)"),
                            ("error", "Falhou"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="situação",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False,
                        help_text="Nada foi gravado além deste registro.",
                        verbose_name="simulação",
                    ),
                ),
                (
                    "item_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="limite de itens"
                    ),
                ),
                (
                    "items_seen",
                    models.PositiveIntegerField(default=0, verbose_name="itens vistos"),
                ),
                (
                    "items_new",
                    models.PositiveIntegerField(default=0, verbose_name="novos"),
                ),
                (
                    "items_updated",
                    models.PositiveIntegerField(default=0, verbose_name="atualizados"),
                ),
                (
                    "items_failed",
                    models.PositiveIntegerField(default=0, verbose_name="com falha"),
                ),
                (
                    "error_log",
                    models.TextField(
                        blank=True,
                        help_text="Só o tipo e a mensagem do erro, sem o conteúdo dos itens (logs públicos).",
                        verbose_name="erros",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.source",
                        verbose_name="fonte",
                    ),
                ),
            ],
            options={
                "verbose_name": "execução de coleta",
                "verbose_name_plural": "execuções de coleta",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RawDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=1000, unique=True, verbose_name="URL"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        default=200, verbose_name="status HTTP"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="tipo de conteúdo"
                    ),
                ),
                (
                    "etag",
                    models.CharField(blank=True, max_length=255, verbose_name="ETag"),
                ),
                (
                    "last_modified",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Last-Modified"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="hash do conteúdo (SHA-256)",
                    ),
                ),
                (
                    "text_gz",
                    models.BinaryField(
                        blank=True, default=bytes, verbose_name="texto comprimido"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tamanho do texto (bytes)"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="baixado em"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        default=collection.models.default_expiry,
                        help_text="Depois disso `purge_raw_documents` apaga o texto e mantém URL e hash.",
                        null=True,
                        verbose_name="expira em",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_documents",
                        to="core.source",
                        verbose_name="fonte",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento bruto",
                "verbose_name_plural": "documentos brutos",
                "ordering": ["-fetched_at"],
            },
        ),
    ]
