# Generated by Django 5.2.17 on 2026-10-01 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20, verbose_name="provedor")),
                (
                    "query_key",
                    models.CharField(
                        help_text="Sem acentos, caixa e pontuação.",
                        max_length=300,
                        verbose_name="consulta normalizada",
                    ),
                ),
                ("query", models.CharField(max_length=300, verbose_name="consulta")),
                ("results", models.JSONField(default=list, verbose_name="resultados")),
                (
                    "searched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="feita em"
                    ),
                ),
            ],
            options={
                "verbose_name": "busca web",
                "verbose_name_plural": "buscas web",
                "ordering": ["-searched_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "query_key"), name="uniq_search_query"
                    )
                ],
            },
        ),
    ]
