# Generated by Django 5.2.17 on 2026-10-01 22:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="ID da entidade"),
                ),
                (
                    "profile",
                    models.CharField(
                        help_text="Ex.: opp.edital.",
                        max_length=40,
                        verbose_name="perfil",
                    ),
                ),
                (
                    "scoring_version",
                    models.CharField(max_length=20, verbose_name="versão da pontuação"),
                ),
                (
                    "total",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="De 0 a 100. Vazio quando a entidade foi barrada por um gate.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="pontos",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("prioritize", "Priorizar"),
                            ("evaluate", "Avaliar"),
                            ("low", "Baixa"),
                            ("ignore", "Ignorar"),
                            ("gated", "Bloqueada"),
                        ],
                        max_length=10,
                        verbose_name="rótulo",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="confiança (K)",
                    ),
                ),
                (
                    "gated",
                    models.BooleanField(default=False, verbose_name="barrada por gate"),
                ),
                (
                    "gate_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("expired", "Prazo vencido ou já ocorreu"),
                            ("territory", "Território inelegível"),
                            (
                                "company_requirement",
                                "Requisito da empresa não atendido",
                            ),
                        ],
                        max_length=20,
                        verbose_name="tipo do gate",
                    ),
                ),
                (
                    "gate_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="motivo do gate"
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lista de {"factor", "label", "raw", "weight", "points", "explanation", "evidence_ids", "support"}.',
                        verbose_name="detalhamento",
                    ),
                ),
                (
                    "alerts",
                    models.JSONField(blank=True, default=list, verbose_name="alertas"),
                ),
                (
                    "raw_sum",
                    models.FloatField(
                        blank=True, null=True, verbose_name="soma ponderada"
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="calculado em"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "core"),
                            ("model__in", ("organization", "opportunity")),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="tipo da entidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "pontuação",
                "verbose_name_plural": "pontuações",
                "ordering": [
                    models.OrderBy(models.F("total"), descending=True, nulls_last=True),
                    "-computed_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="score_entity_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id"), name="uniq_score_entity"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("total__isnull", True),
                            models.Q(("total__gte", 0), ("total__lte", 100)),
                            _connector="OR",
                        ),
                        name="score_total_in_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("gated", False), ("total__isnull", False)),
                            models.Q(("gated", True), ("total__isnull", True)),
                            _connector="OR",
                        ),
                        name="score_gated_iff_no_total",
                    ),
                ],
            },
        ),
    ]
