# Generated by Django 5.2.17 on 2026-10-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="gate_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expired", "Prazo vencido ou já ocorreu"),
                    ("territory", "Território inelegível"),
                    ("company_requirement", "Requisito da empresa não atendido"),
                    ("do_not_contact", "Não contatar (opt-out)"),
                ],
                max_length=20,
                verbose_name="tipo do gate",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="label",
            field=models.CharField(
                choices=[
                    ("prioritize", "Priorizar"),
                    ("evaluate", "Avaliar"),
                    ("low", "Baixa"),
                    ("ignore", "Ignorar"),
                    ("gated", "Bloqueada"),
                    ("ongoing", "Em andamento"),
                ],
                max_length=10,
                verbose_name="rótulo",
            ),
        ),
    ]
