# Generated by Django 5.2.17 on 2026-10-01 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="quando",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="tarefa"
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        help_text="provedor:modelo",
                        max_length=120,
                        verbose_name="estratégia",
                    ),
                ),
                ("provider", models.CharField(max_length=30, verbose_name="provedor")),
                ("model", models.CharField(max_length=80, verbose_name="modelo")),
                (
                    "billing",
                    models.CharField(
                        help_text="free · credits (AI Pro) · money (dinheiro novo)",
                        max_length=10,
                        verbose_name="cobrança",
                    ),
                ),
                (
                    "data_class",
                    models.CharField(max_length=10, verbose_name="classe do dado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Concluída"),
                            ("cached", "Do cache (custo 0)"),
                            ("invalid", "Resposta fora do schema"),
                            ("rate_limited", "Cota esgotada (429)"),
                            ("error", "Erro do provedor"),
                        ],
                        max_length=14,
                        verbose_name="situação",
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="versão do prompt"
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="chave de cache",
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de entrada"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de saída"
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="custo (US$)",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="duração (ms)"),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        help_text="Sem conteúdo.",
                        max_length=200,
                        verbose_name="erro",
                    ),
                ),
                (
                    "response_text",
                    models.TextField(blank=True, verbose_name="resposta (cache)"),
                ),
            ],
            options={
                "verbose_name": "chamada de IA",
                "verbose_name_plural": "chamadas de IA",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cache_key", "status"],
                        name="llm_llmcall_cache_k_f66159_idx",
                    )
                ],
            },
        ),
    ]
